language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.1
  - 7
  - 5.6
  - nightly
  - hhvm

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/behat --config=tests/behat.yml --format=progress --strict

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
