language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - composer install --dev --prefer-source --no-interaction
  
script:
  - ./bin/phpunit -c tests
  - ./bin/behat --config=tests/behat.yml --format=progress --strict

matrix:
  allow_failures:
    - php: hhvm
